version: '3.9'

services:
  criptojournal_app:
    build:
      context: .
      dockerfile: Dockerfile

    image: criptojournal:latest
    container_name: kmz_criptojournal
    restart: unless-stopped

    networks:
      - nginx-network
      - dbmysql-network

    volumes:
      - public_data:/var/www/public

    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://10.1.53.220:8005
      APP_KEY: base64:bQFhlf4lMqXKMZXwGUzrEe0lAs3qYNkW/Zz1Q165378=
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: KMZ_cripto_journal
      DB_USERNAME: UserKmz001
      DB_PASSWORD: 'PassKmz2026$'

networks:
  nginx-network:
    external: true

  dbmysql-network:
    external: true

volumes:
  public_data:
    name: criptojournal_public
